<?php

return [
    [
        'name' => 'title',
        'title' => '标题',
        'type' => 'string',
        'content' => [],
        'value' => '示例标题',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'theme',
        'title' => '皮肤',
        'type' => 'string',
        'content' => [],
        'value' => 'default',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'domain',
        'title' => '绑定二级域名前缀',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'index/index' => '/example$',
            'demo/index' => '/example/d/[:name]',
            'demo/demo1' => '/example/d1/[:name]',
            'demo/demo2' => '/example/d2/[:name]',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
